---
kind: pipeline
type: ssh
name: create-docker-images

server:
  host: 192.168.72.8:2022
  user: root
  ssh_key:
    from_secret: ssh_key_umac

steps:
- name: build_and_push_master
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - pwd
  - git checkout master
  - echo $PASSWORD | docker login -u $USERNAME --password-stdin
  - docker buildx create --name multiarch1 --driver docker-container --use
  - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag andrey0001/unbound-tls .
  when:
    branch:
    - master
    event:
    - tag
- name: build_and_push_s6
  commands:
  - pwd
  - git fetch --all
  - git checkout s6
  - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag andrey0001/unbound-tls:s6 .
  when:
    branch:
    - s6
    event:
    - tag

node:
  instance: umac
  type: ssh
  
  