---
kind: pipeline
type: ssh
name: create-docker-images

server:
  host: 192.168.72.8:2022
  user: root
  ssh_key:
    from_secret: ssh_key_umac

steps:
- name: git_login
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - echo $PASSWORD | docker login -u $USERNAME --password-stdin
  - docker buildx create --name multiarch1 --driver docker-container --use
  when:
    event:
    - promote
    
- name: build_test_master
  commands:
  - docker build --tag andrey0001/unbound-tls:latest .
  - docker run --detach --name build_test_master_unbound-tls -p 5753:53 -p 5753:53/udp -d andrey0001/unbound-tls:latest
  - sleep 10; dig a -p 5753 @127.0.0.1 google.com
  - docker stop build_test_master_unbound-tls; docker rm build_test_master_unbound-tls
  - docker rmi andrey0001/unbound-tls:latest
  when:
    branch:
    - master  

- name: build_and_push_master
  commands:
  - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag andrey0001/unbound-tls .
  when:
    branch:
    - master
    event:
    - promote

- name: build_s6
  commands:
  - docker build --tag andrey0001/unbound-tls:s6 .
  - docker rmi andrey0001/unbound-tls:s6
  when:
    branch:
    - s6  

- name: build_and_push_s6
  commands:
  - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag andrey0001/unbound-tls:s6 .
  when:
    branch:
    - s6
    event:
    - promote

node:
  instance: umac
  type: ssh