---
kind: pipeline
type: ssh
name: create-docker-images

server:
  host: 192.168.72.8:2022
  user: root
  ssh_key:
    from_secret: ssh_key_umac
  
steps:
- name: build_and_push_s6
  commands:
  - ls -al

node:
  instance: umac
  type: ssh
