version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    hostname: pihole
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Asia/Jerusalem'
      WEBPASSWORD: PassWord
      PIHOLE_DNS_: "10.8.1.3"
    volumes:
      - /opt/pihole/etc:/etc/pihole/
      - /opt/pihole/dnsmasq:/etc/dnsmasq.d/
    restart: unless-stopped
    networks:
      pihole-unbound-dns:
        ipv4_address: 10.8.1.2
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     resources:
      limits:
        cpus: '0.50'
        memory: 768M
      reservations:
        cpus: '0.2'
        memory: 512M

  unbound:
    image: andrey0001/unbound-tls:latest
    hostname: unbound-tls
    container_name: unbound-tls
    restart: unless-stopped
    volumes:
      - /opt/unbound-tls:/etc/unbound/unbound.conf.d
    networks:
      pihole-unbound-dns:
        ipv4_address: 10.8.1.3
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     resources:
      limits:
        cpus: '0.30'
        memory: 256M
      reservations:
        cpus: '0.1'
        memory: 128M

networks:
  pihole-unbound-dns:
    ipam:
      config:
        - subnet: 10.8.1.0/29
