version: "3.8"
  unbound:
    image: andrey0001/unbound-tls:s6
    hostname: unbound-tls
    container_name: unbound-tls
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    volumes:
      - /opt/unbound-tls:/etc/unbound/unbound.conf.d

