version: "3.8"
services:
  unbound:
    image: andrey0001/unbound-tls:latest
    hostname: unbound-tls
    container_name: unbound-tls
    network_mode: bridge
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    volumes:
      - /opt/unbound-tls:/etc/unbound/unbound.conf.d
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
    deploy:
     resources:
      limits:
        cpus: '0.30'
        memory: 256M
      reservations:
        cpus: '0.1'
        memory: 128M
