name: docker-build-s6

on:
  push:
    branches:
      - "s6"

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}         

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/} ${{ BRANCH_NAME}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: andrey0001/unbound-tls:${{ BRANCH_NAME}}

